repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args:
          - "--maxkb=10000"
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: detect-private-key
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: markdown-link-check
  - repo: https://github.com/hadolint/hadolint
    rev: v1.22.1
    hooks:
      - id: hadolint
