name: Lint

on:
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.20.1
        with:
          github_token: ${{ secrets.GH_PAT }}
          reporter: github-pr-review
