name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Get current tag name
        id: tagName
        uses: olegtarasov/get-tag@v2.1
        with:
          tagRegex: "(?<package>.+)-(?<version>((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?))"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to Docker Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push to Docker Registry
        uses: docker/build-push-action@v2.7.0
        with:
          context: "${{ steps.tagName.outputs.package }}"
          push: true
          tags: |
            ghcr.io/skyoo2003/${{ steps.tagName.outputs.package }}:latest
            ghcr.io/skyoo2003/${{ steps.tagName.outputs.package }}:${{ steps.tagName.outputs.version }}
