name: "Stale"

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5.1.1
        with:
          repo-token: ${{ secrets.GH_PAT }}
          stale-issue-message: >
            This issue is stale because it has been open 30 days with no activity.
            Remove stale label or comment or this will be closed in 5 days.
          stale-pr-message: >
            This pull request is stale because it has been open 30 days with no activity.
            Remove stale label or comment or this will be closed in 5 days.
          stale-issue-label: "stale"
          exempt-issue-labels: "wip"
          stale-pr-label: "stale"
          exempt-pr-labels: "wip"
          days-before-stale: 30
          days-before-close: 5
